let TestABlineDebug = require('debug')('tom:TestABLine')
let mf = require('./mf.json')
let TomABLine = require('../lib/TomABLine')
let ABLine = new TomABLine(5.0,2.0)
ABLine.ABLine(mf)
const {vec3, vec2} = require('../lib/vec3')
let pivot = new vec3(0.0, 0.0, 0.7)
TestABlineDebug(ABLine)
ABLine.BuildCurrentABLineList(pivot)
TestABlineDebug(ABLine)

